name: Deploy to AWS

on:
  push:
    branches:
      - main  # O la rama que desees usar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

      - name: Copy JAR to EC2
        run: scp -i sinfonia2.pem PI-Back-0.0.1-SNAPSHOT.jar ec2-user@18.232.163.145:/home/ec2-user/

      - name: SSH into EC2 and stop existing process
        run: |
          ssh -i sinfonia2.pem ec2-user@18.232.163.145 "ps aux | grep PI-Back-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print \$2}' | xargs -r kill"

      - name: SSH into EC2 and start JAR in background
        run: |
          ssh -i sinfonia2.pem ec2-user@18.232.163.145 "nohup java -jar /home/ec2-user/PI-Back-0.0.1-SNAPSHOT.jar > output.log 2>&1 &"
